spring:
  application:
    name: got
  profiles:
    active: default
  config:
    import: "optional:configserver:http://localhost:8071/"
server:
  port: 8090


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "Game Of Thrones"
    description: "Nine noble families wage war against each other in order to gain control over the mythical land of Westeros. Meanwhile, a force is rising after millenniums and threatens the existence of living men."
    version: "1.0.0"

