server:
  port: 8110

spring:
  application:
    name: series
  datasource:
    url: jdbc:mysql://localhost:3306/seriesdb
    username: root
    password: 11101996
  jpa:
    show-sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"