server:
  port: 8080
spring:
  application:
    name: office
  profiles:
    active: "production"
  datasource:
    url: jdbc:mysql://localhost:3306/episodedb
    username: root
    password: 11101996
  jpa:
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
management:
  endpoints:
    web:
      exposure:
        include: "*"
