server:
    port: 8070

spring:
  application:
      name: friends
  datasource:
      url: jdbc:mysql://localhost:3306/episodedb
      username: root
      password: 11101996
  jpa:
      show-sql: true
