server:
  port: 8080
spring:
  application:
    name: office
  datasource:
    url: jdbc:mysql://localhost:3306/episodedb
    username: root
    password: 11101996
  jpa:
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/