spring:
  application:
      name: friends
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8071/



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "friends"
    description: "F.r.i.e.n.d.s. "
    version: "1.0.0"