server:
  port: 8090

spring:
  application:
    name: got
  data:
    mongodb:
      uri: mongodb://localhost:27017/episodes

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/